### ISSUE TITLE
Sidecar OOM

### ISSUE THREAD

**Issue by wneirynck** [monkey-projects/monkeyci#193]
When restoring a larger workspace (+250M) the sidecar goes OOM.  Increasing job memory does not help, probably the max memory limit is reached (see JVM memory calculation).

Stack trace:
```
2024-07-31T14:07:05.447056569Z stderr F Exception in thread "I/O dispatcher 2" java.lang.OutOfMemoryError: Java heap space
2024-07-31T14:07:05.447266612Z stderr F 	at java.base/java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:71)
2024-07-31T14:07:05.447405814Z stderr F 	at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:391)
2024-07-31T14:07:05.447482215Z stderr F 	at org.apache.http.nio.util.HeapByteBufferAllocator.allocate(HeapByteBufferAllocator.java:52)
2024-07-31T14:07:05.447543776Z stderr F 	at org.apache.http.nio.util.ExpandableBuffer.expandCapacity(ExpandableBuffer.java:109)
2024-07-31T14:07:05.447597857Z stderr F 	at org.apache.http.nio.util.ExpandableBuffer.expand(ExpandableBuffer.java:140)
2024-07-31T14:07:05.447668658Z stderr F 	at org.apache.http.nio.util.SimpleInputBuffer.consumeContent(SimpleInputBuffer.java:69)
2024-07-31T14:07:05.447762659Z stderr F 	at org.apache.http.nio.protocol.BasicAsyncResponseConsumer.onContentReceived(BasicAsyncResponseConsumer.java:85)
2024-07-31T14:07:05.458637256Z stderr F 	at org.apache.http.nio.protocol.AbstractAsyncResponseConsumer.consumeContent(AbstractAsyncResponseConsumer.java:147)
2024-07-31T14:07:05.458753937Z stderr F 	at org.apache.http.impl.nio.client.MainClientExec.consumeContent(MainClientExec.java:329)
2024-07-31T14:07:05.45890782Z stderr F 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.consumeContent(DefaultClientExchangeHandlerImpl.java:157)
2024-07-31T14:07:05.459262585Z stderr F 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:330)
2024-07-31T14:07:05.459908994Z stderr F 	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
2024-07-31T14:07:05.460321Z stderr F 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
2024-07-31T14:07:05.460490482Z stderr F 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
2024-07-31T14:07:05.460580084Z stderr F 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
2024-07-31T14:07:05.460641284Z stderr F 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
2024-07-31T14:07:05.460743166Z stderr F 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
2024-07-31T14:07:05.460804087Z stderr F 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
2024-07-31T14:07:05.460955729Z stderr F 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
2024-07-31T14:07:05.46103893Z stderr F 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
2024-07-31T14:07:05.461216813Z stderr F 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
2024-07-31T14:07:05.461371255Z stderr F 	at java.base/java.lang.Thread.runWith(Thread.java:1596)
2024-07-31T14:07:05.462000024Z stderr F 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Somehow we're using an Apache HttpClient and it's allocating a large chunk and erroring out.  Ideally we can stream the response without having to allocate a lot of memory, and/or the sidecar can access the full memory of the job.

This can be reproduced on the journal private repo, which has a lot of binary files (images).

**Comment by wneirynck** [comment]
[clj-http](https://github.com/dakrone/clj-http) is using Apache http client underneath.  We specifically switched to that lib to be able to use streaming, so must be that it's not working after all, or some setting is not correct.

**Comment by wneirynck** [comment]
Fixed by replacing clj-http with aleph
